algoritmo "Exercicio 10"
var  largura, altura, calculo, quantidade : real

inicio
         escreval("insira a largura da parede : ")
         leia(largura)
         escreval("insira a altura da parede : ")
         leia(altura)
         calculo <- largura*altura
         quantidade <-calculo/2
         escreval("A area da sua parede é : ",calculo,"m² e voce ira gastar, ",quantidade,"L de tinta")
fimalgoritmo