algoritmo "Exercicio 8"
var  metros : real


inicio
         escreva("insira uma distancia em metros: ")
         leia  (metros)
         escreval("A distancia em km é de : ", metros/1000)
         escreval("A distancia em Hm é de : ",metros/100)
         escreval("A distancia em Dam é de : ",metros/10)
         escreval("A distancia em Dm é de : ",metros*10)
         escreval("A distancia entre Cm é de : ",metros*100)
         escreval("A distancia entre mm é de : ",metros*1000)
fimalgoritmo