algoritmo "Exercicio 14"
var   kmPercorrido, quantidadeDias, resultado : real

inicio
           escreval("insira a quantidade de Km percorrido : ")
           leia(kmPercorrido)
           escreval("insira a quantidade de dias alugados : ")
           leia(quantidadeDias)
           resultado<- (kmPercorrido*0.20)+(quantidadeDias*90)
           escreval("O valor total a ser pago é de : ",resultado)
fimalgoritmo