Algoritmo "Exercicio 44"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/09/2022
Var
ini, fim, inc, cont : inteiro


Inicio

escreval("insira o valor de inicio")
leia(ini)
escreval("insira o valor final")
leia(fim)
escreval("insira o incremento")
leia(inc)
cont <-ini+cont
enquanto((cont<=fim)faca
escreval(cont)
cont<-cont+inc

fimenquanto


Fimalgoritmo