Algoritmo "semnome"
// Disciplina   : Algoritimo curso em video
// Professor   : guanabara 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Delson Filho
// Data atual  : 28/07/2022
Var
numero1, numero2, soma : real


Inicio
escreval ("insira um número para a soma: ")
leia (numero1)
escreval ("insira segundo número para a soma: ")
leia (numero2)
soma <- numero1+numero2
escreval ("O resultado de ", numero1," +", numero2, " é: ", soma)

Fimalgoritmo